FROM node:24-alpine

WORKDIR /app

COPY package*.json ./

ENV NODE_OPTIONS="--max-old-space-size=4096"

RUN npm ci --no-audit --no-fund

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]