# Generated by Django 6.0.4 on 2026-05-08 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha de salida')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=20, unique=True, verbose_name='Referencia')),
                ('description', models.CharField(max_length=150, verbose_name='Descripción')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('safety_stock', models.IntegerField(default=0, verbose_name='Stock bajo mínimos')),
                ('safety_warning', models.BooleanField(default='True', verbose_name='Aviso de stock bajo mínimos')),
                ('observations', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observaciones')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.location', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item', verbose_name='Artículo')),
                ('withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.withdrawal', verbose_name='Salida')),
            ],
            options={
                'verbose_name': 'Linea de salida',
                'verbose_name_plural': 'Lineas de salida',
            },
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.worker', verbose_name='Empleado'),
        ),
    ]
