# Generated by Django 6.0.4 on 2026-04-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albalinea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codalbaran', models.IntegerField()),
                ('numlinea', models.IntegerField()),
                ('codfamilia', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=15, null=True)),
                ('cantidad', models.FloatField()),
                ('precio', models.FloatField()),
                ('importe', models.FloatField()),
                ('dcto', models.IntegerField()),
            ],
            options={
                'db_table': 'albalinea',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Albaranes',
            fields=[
                ('codalbaran', models.AutoField(primary_key=True, serialize=False)),
                ('codfactura', models.IntegerField()),
                ('fecha', models.DateField()),
                ('iva', models.IntegerField()),
                ('codcliente', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=1, null=True)),
                ('totalalbaran', models.FloatField()),
                ('borrado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'albaranes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Albaranesp',
            fields=[
                ('pk', models.CompositePrimaryKey('codalbaran', 'codproveedor', blank=True, editable=False, primary_key=True, serialize=False)),
                ('codalbaran', models.CharField(max_length=20)),
                ('codproveedor', models.IntegerField()),
                ('codfactura', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateField()),
                ('iva', models.IntegerField()),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
                ('totalalbaran', models.FloatField()),
            ],
            options={
                'db_table': 'albaranesp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Albaranesptmp',
            fields=[
                ('codalbaran', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'albaranesptmp',
                'db_table_comment': 'Temporal de albaranes de proveedores para controlar acceso s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Albaranestmp',
            fields=[
                ('codalbaran', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'albaranestmp',
                'db_table_comment': 'Temporal de albaranes para controlar acceso simultaneo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('codarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('codfamilia', models.IntegerField()),
                ('referencia', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('impuesto', models.FloatField()),
                ('codproveedor1', models.IntegerField()),
                ('codproveedor2', models.IntegerField()),
                ('descripcion_corta', models.CharField(max_length=30)),
                ('codubicacion', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('aviso_minimo', models.CharField(max_length=1)),
                ('datos_producto', models.CharField(max_length=200)),
                ('fecha_alta', models.DateField()),
                ('codembalaje', models.IntegerField()),
                ('unidades_caja', models.IntegerField()),
                ('precio_ticket', models.CharField(max_length=1)),
                ('modificar_ticket', models.CharField(max_length=1)),
                ('observaciones', models.TextField()),
                ('precio_compra', models.FloatField(blank=True, null=True)),
                ('precio_almacen', models.FloatField(blank=True, null=True)),
                ('precio_tienda', models.FloatField(blank=True, null=True)),
                ('precio_pvp', models.FloatField(blank=True, null=True)),
                ('precio_iva', models.FloatField(blank=True, null=True)),
                ('codigobarras', models.CharField(max_length=15)),
                ('imagen', models.CharField(max_length=200)),
                ('borrado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'articulos',
                'db_table_comment': 'Articulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artpro',
            fields=[
                ('pk', models.CompositePrimaryKey('codarticulo', 'codfamilia', 'codproveedor', blank=True, editable=False, primary_key=True, serialize=False)),
                ('codarticulo', models.CharField(max_length=15)),
                ('codfamilia', models.IntegerField()),
                ('codproveedor', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'artpro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('codcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('nif', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=50)),
                ('codprovincia', models.IntegerField()),
                ('localidad', models.CharField(max_length=35)),
                ('codformapago', models.IntegerField()),
                ('codentidad', models.IntegerField()),
                ('cuentabancaria', models.CharField(max_length=20)),
                ('codpostal', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=14)),
                ('movil', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=35)),
                ('web', models.CharField(max_length=45)),
                ('borrado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'clientes',
                'db_table_comment': 'Clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cobros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codfactura', models.IntegerField()),
                ('codcliente', models.IntegerField()),
                ('importe', models.FloatField()),
                ('codformapago', models.IntegerField()),
                ('numdocumento', models.CharField(max_length=30)),
                ('fechacobro', models.DateField()),
                ('observaciones', models.TextField()),
            ],
            options={
                'db_table': 'cobros',
                'db_table_comment': 'Cobros de facturas a clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Embalajes',
            fields=[
                ('codembalaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('borrado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'embalajes',
                'db_table_comment': 'Embalajes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('codentidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombreentidad', models.CharField(max_length=50)),
                ('borrado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'entidades',
                'db_table_comment': 'Entidades Bancarias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factulinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codfactura', models.IntegerField()),
                ('numlinea', models.IntegerField()),
                ('codfamilia', models.IntegerField()),
                ('codigo', models.CharField(max_length=15)),
                ('cantidad', models.FloatField()),
                ('precio', models.FloatField()),
                ('importe', models.FloatField()),
                ('dcto', models.IntegerField()),
            ],
            options={
                'db_table': 'factulinea',
                'db_table_comment': 'lineas de facturas a clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('codfactura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('iva', models.IntegerField()),
                ('codcliente', models.IntegerField()),
                ('estado', models.CharField(max_length=1)),
                ('totalfactura', models.FloatField()),
                ('fechavencimiento', models.DateField()),
                ('borrado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'facturas',
                'db_table_comment': 'facturas de ventas a clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturasp',
            fields=[
                ('pk', models.CompositePrimaryKey('codfactura', 'codproveedor', blank=True, editable=False, primary_key=True, serialize=False)),
                ('codfactura', models.CharField(max_length=20)),
                ('codproveedor', models.IntegerField()),
                ('fecha', models.DateField()),
                ('iva', models.IntegerField()),
                ('estado', models.CharField(max_length=1)),
                ('totalfactura', models.FloatField()),
                ('fechapago', models.DateField()),
                ('borrado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'facturasp',
                'db_table_comment': 'facturas de compras a proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturasptmp',
            fields=[
                ('codfactura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'facturasptmp',
                'db_table_comment': 'temporal de facturas de proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturastmp',
            fields=[
                ('codfactura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'facturastmp',
                'db_table_comment': 'temporal de facturas a clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Familias',
            fields=[
                ('codfamilia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('borrado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'familias',
                'db_table_comment': 'familia de articulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formapago',
            fields=[
                ('codformapago', models.AutoField(primary_key=True, serialize=False)),
                ('nombrefp', models.CharField(max_length=40)),
                ('borrado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'formapago',
                'db_table_comment': 'Forma de pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('codimpuesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('valor', models.FloatField()),
                ('borrado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'impuestos',
                'db_table_comment': 'tipos de impuestos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Librodiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipodocumento', models.CharField(max_length=1)),
                ('coddocumento', models.CharField(max_length=20)),
                ('codcomercial', models.IntegerField()),
                ('codformapago', models.IntegerField()),
                ('numpago', models.CharField(max_length=30)),
                ('total', models.FloatField()),
            ],
            options={
                'db_table': 'librodiario',
                'db_table_comment': 'Movimientos diarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codfactura', models.CharField(max_length=20)),
                ('codproveedor', models.IntegerField()),
                ('importe', models.FloatField()),
                ('codformapago', models.IntegerField()),
                ('numdocumento', models.CharField(max_length=30)),
                ('fechapago', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField()),
            ],
            options={
                'db_table': 'pagos',
                'db_table_comment': 'Pagos de facturas a proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('codproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('nif', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=50)),
                ('codprovincia', models.IntegerField()),
                ('localidad', models.CharField(max_length=35)),
                ('codentidad', models.IntegerField()),
                ('cuentabancaria', models.CharField(max_length=20)),
                ('codpostal', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=14)),
                ('movil', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=35)),
                ('web', models.CharField(max_length=45)),
                ('borrado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'proveedores',
                'db_table_comment': 'Proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('codprovincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombreprovincia', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'provincias',
                'db_table_comment': 'Provincias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tabbackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(db_collation='utf8mb3_unicode_ci', max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('archivo', models.CharField(db_collation='utf8mb3_unicode_ci', max_length=40)),
            ],
            options={
                'db_table': 'tabbackup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('codubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('borrado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'ubicaciones',
                'db_table_comment': 'Ubicaciones',
                'managed': False,
            },
        ),
    ]
