# Generated by Django 6.0.4 on 2026-05-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(max_length=15, unique=True, verbose_name='Código'),
        ),
    ]
